// `@upstash/agentkit-tanstack-ai/persistence` — every TanStack AI persistence store on Upstash Redis
// (and Upstash Blob for generated bytes). Needs `@tanstack/ai-persistence`.
export { upstashPersistence } from "./persistence.js";
export type { UpstashPersistenceConfig, UpstashPersistenceStores } from "./persistence.js";

// Blob store (bytes in Upstash Blob, records in Redis) — included by upstashPersistence({ bucket }).
export { upstashBlobStore } from "./blob-store.js";
export type { BlobBucketLike, UpstashBlobStoreConfig } from "./blob-store.js";
