import type { Redis } from "@upstash/redis";
import { Redis as RedisClient } from "@upstash/redis";
import type { ModelMessage, RunRecord, RunStore } from "@tanstack/ai";
import type {
  AIPersistence,
  ArtifactStore,
  BlobStore,
  ChatPersistenceStores,
  GenerationRunStore,
  InterruptRecord,
  InterruptStore,
  MessageStore,
  MetadataStore,
} from "@tanstack/ai-persistence";
import { addTelemetry } from "../telemetry.js";
import {
  CREATE,
  KEY_LOCKING,
  PATCH,
  assertId,
  checkRun,
  loadDocs,
  toMergePatches,
} from "./records.js";
import { redisArtifactStore, redisGenerationRunStore } from "./generation-stores.js";
import { upstashBlobStore } from "./blob-store.js";
import type { BlobBucketLike } from "./blob-store.js";

export interface UpstashPersistenceConfig {
  /** Upstash Redis client. Defaults to `Redis.fromEnv()`. */
  redis?: Redis;
  /** Base key prefix. Defaults to `agentkit:tanstack`. */
  prefix?: string;
  /**
   * Expire a thread's stored transcript this many seconds after its last save. Omit to keep
   * transcripts forever. Run, interrupt and metadata records are never expired automatically.
   */
  messagesTtlSeconds?: number;
  /**
   * An Upstash Blob bucket (e.g. `Bucket.fromEnv()` from `@upstash/blob`). When given, a `blobs`
   * store is included: generated bytes (images, audio, video) go to the bucket, their records to
   * Redis. Without it the persistence has no `blobs` store.
   */
  bucket?: BlobBucketLike;
  /**
   * Path prefix for objects written to `bucket`.
   * @default "agentkit/tanstack/"
   */
  blobPathPrefix?: string;
  /**
   * Report the sdk name + version to Upstash as a header on the requests made by your redis client.
   * Can also be disabled with the `UPSTASH_DISABLE_TELEMETRY` env var. Defaults to `true`.
   */
  enableTelemetry?: boolean;
}

/** The stores {@link upstashPersistence} returns; `blobs` is present when a `bucket` is passed. */
export type UpstashPersistenceStores = ChatPersistenceStores & {
  generationRuns: GenerationRunStore;
  artifacts: ArtifactStore;
  blobs?: BlobStore;
};

/**
 * Settle a batch of interrupts atomically: every document must exist and be pending, or nothing
 * changes. ARGV[i] is the merge patch for KEYS[i].
 */
const COMMIT_BATCH = `${KEY_LOCKING}for i = 1, #KEYS do
  local status = redis.call("JSON.GET", KEYS[i], "$.status")
  if not status then return redis.error_reply("missing:" .. i) end
  if status ~= '["pending"]' then return redis.error_reply("nonpending:" .. i) end
end
for i = 1, #KEYS do redis.call("JSON.MERGE", KEYS[i], "$", ARGV[i]) end
return #KEYS`;

/**
 * {@link PATCH} for a run that also keeps the detached-runs index in step with the patched record, in
 * the same script, so a crash or a racing update can never leave a detached run out of the index.
 * KEYS: run document, detached index. ARGV: the two merge patches, runId.
 */
const UPDATE_RUN = `${KEY_LOCKING}if redis.call("EXISTS", KEYS[1]) == 0 then return 0 end
redis.call("JSON.MERGE", KEYS[1], "$", ARGV[1])
if ARGV[2] ~= "{}" then redis.call("JSON.MERGE", KEYS[1], "$", ARGV[2]) end
local status = redis.call("JSON.GET", KEYS[1], "$.status")
local since = string.sub(redis.call("JSON.GET", KEYS[1], "$.detachedSince"), 2, -2)
if status == '["running"]' and tonumber(since) then
  redis.call("ZADD", KEYS[2], since, ARGV[3])
else
  redis.call("ZREM", KEYS[2], ARGV[3])
end
return 1`;

/**
 * Every TanStack AI persistence store on Upstash Redis — pass the result to `withPersistence()` or
 * `withGenerationPersistence()`.
 *
 * - **messages**: the thread transcript, one JSON document per thread (`saveThread` overwrites).
 * - **runs**: a JSON document per run plus sorted-set indexes by thread, by parent run and by detach
 *   time, so `findActiveRun`, `listByThread`, `listByParentRun` and `listReclaimable` are index reads.
 * - **interrupts**: human-in-the-loop pauses, indexed by thread and run; `commitBatch` is atomic.
 * - **metadata**: one document per `(namespace, key)`, both parts escaped so they never collide.
 * - **generationRuns** / **artifacts**: one-shot generation jobs (image, video, speech) and records of
 *   what they produced.
 * - **blobs** (when `bucket` is given): the produced bytes in Upstash Blob, records in Redis.
 *
 * Records are RedisJSON documents written by single commands or single Lua scripts, so concurrent
 * instances cannot interleave a write. Checked against TanStack's `runPersistenceConformance` suite.
 *
 * ```ts
 * import { withPersistence } from "@tanstack/ai-persistence";
 * import { upstashPersistence } from "@upstash/agentkit-tanstack-ai/persistence";
 *
 * chat({ adapter, messages, threadId, middleware: [withPersistence(upstashPersistence())] });
 * ```
 */
export function upstashPersistence(
  config: UpstashPersistenceConfig = {},
): AIPersistence<UpstashPersistenceStores> {
  const redis = config.redis ?? RedisClient.fromEnv();
  addTelemetry(redis, config.enableTelemetry);
  const p = config.prefix ?? "agentkit:tanstack";
  const k = {
    thread: (id: string) => `${p}:thread:${id}`,
    run: (id: string) => `${p}:run:${id}`,
    threadRuns: (id: string) => `${p}:threadRuns:${id}`,
    parentRuns: (id: string) => `${p}:parentRuns:${id}`,
    detached: `${p}:detachedRuns`,
    interrupt: (id: string) => `${p}:interrupt:${id}`,
    threadInterrupts: (id: string) => `${p}:threadInterrupts:${id}`,
    runInterrupts: (id: string) => `${p}:runInterrupts:${id}`,
    // encodeURIComponent never emits ":", so (namespace, key) pairs cannot collide.
    meta: (ns: string, key: string) =>
      `${p}:meta:${encodeURIComponent(ns)}:${encodeURIComponent(key)}`,
  };

  const loadRuns = async (ids: string[]) =>
    (await loadDocs<RunRecord>(redis, ids.map(k.run))).map((r) => checkRun(r)!);
  const loadInterrupts = (ids: string[]) => loadDocs<InterruptRecord>(redis, ids.map(k.interrupt));
  const patch = (key: string, fields: object) => redis.eval(PATCH, [key], toMergePatches(fields));

  const messages: MessageStore = {
    loadThread: (async (threadId: string) => {
      assertId(threadId, "threadId");
      return (await redis.json.get<ModelMessage[]>(k.thread(threadId))) ?? [];
    }) as MessageStore["loadThread"],
    async saveThread(threadId, list) {
      assertId(threadId, "threadId");
      const tx = redis.multi();
      tx.json.set(k.thread(threadId), "$", list as unknown as Record<string, unknown>);
      if (config.messagesTtlSeconds) tx.expire(k.thread(threadId), config.messagesTtlSeconds);
      await tx.exec();
    },
  };

  const runs: RunStore = {
    async createOrResume(input) {
      assertId(input.runId, "runId");
      assertId(input.threadId, "threadId");
      const record: RunRecord = {
        runId: input.runId,
        threadId: input.threadId,
        status: input.status ?? "running",
        startedAt: input.startedAt,
        ...(input.parentRunId !== undefined ? { parentRunId: input.parentRunId } : {}),
        ...(input.subagentRunId !== undefined ? { subagentRunId: input.subagentRunId } : {}),
        ...(input.name !== undefined ? { name: input.name } : {}),
      };
      const indexes = [k.threadRuns(input.threadId)];
      if (input.parentRunId !== undefined) indexes.push(k.parentRuns(input.parentRunId));
      const stored = await redis.eval(
        CREATE,
        [k.run(input.runId), ...indexes],
        [JSON.stringify(record), String(input.startedAt), input.runId],
      );
      return checkRun(stored as RunRecord)!;
    },

    async update(runId, fields) {
      assertId(runId, "runId");
      if ("detachedSince" in fields || "status" in fields) {
        await redis.eval(
          UPDATE_RUN,
          [k.run(runId), k.detached],
          [...toMergePatches(fields), runId],
        );
      } else {
        await patch(k.run(runId), fields);
      }
    },

    async get(runId) {
      assertId(runId, "runId");
      return checkRun(await redis.json.get<RunRecord>(k.run(runId)));
    },

    async findActiveRun(threadId) {
      assertId(threadId, "threadId");
      const PAGE = 50;
      for (let start = 0; ; start += PAGE) {
        const ids = await redis.zrange<string[]>(k.threadRuns(threadId), start, start + PAGE - 1, {
          rev: true,
        });
        const active = (await loadRuns(ids)).find((r) => r.status === "running");
        if (active) return active;
        if (ids.length < PAGE) return null;
      }
    },

    async listByThread(threadId) {
      assertId(threadId, "threadId");
      return loadRuns(await redis.zrange<string[]>(k.threadRuns(threadId), 0, -1));
    },

    async listByParentRun(parentRunId) {
      assertId(parentRunId, "parentRunId");
      return loadRuns(await redis.zrange<string[]>(k.parentRuns(parentRunId), 0, -1));
    },

    async listReclaimable({ now, ttlMs }) {
      const cutoff = now - ttlMs;
      const ids = await redis.zrange<string[]>(k.detached, "-inf", cutoff, { byScore: true });
      return (await loadRuns(ids)).filter(
        (r) => r.status === "running" && r.detachedSince !== undefined && r.detachedSince <= cutoff,
      );
    },
  };

  const interrupts: InterruptStore = {
    async create(record) {
      assertId(record.interruptId, "interruptId");
      await redis.eval(
        CREATE,
        [
          k.interrupt(record.interruptId),
          k.threadInterrupts(record.threadId),
          k.runInterrupts(record.runId),
        ],
        [
          JSON.stringify({ ...record, status: "pending" }),
          String(record.requestedAt),
          record.interruptId,
        ],
      );
    },

    async resolve(interruptId, response) {
      assertId(interruptId, "interruptId");
      await patch(k.interrupt(interruptId), {
        status: "resolved",
        resolvedAt: Date.now(),
        response,
      });
    },

    async cancel(interruptId) {
      assertId(interruptId, "interruptId");
      await patch(k.interrupt(interruptId), { status: "cancelled", resolvedAt: Date.now() });
    },

    async commitBatch(entries) {
      if (entries.length === 0) return;
      const seen = new Set<string>();
      for (const entry of entries) {
        assertId(entry.interruptId, "interruptId");
        if (seen.has(entry.interruptId)) {
          throw new Error(`Interrupt batch contains duplicate id: ${entry.interruptId}.`);
        }
        seen.add(entry.interruptId);
      }
      const resolvedAt = Date.now();
      // One merge patch per entry. A cancel clears any earlier response (`null` deletes the field).
      const patches = entries.map((e) =>
        JSON.stringify(
          e.status === "resolved"
            ? { status: e.status, resolvedAt, response: e.response ?? null }
            : { status: e.status, resolvedAt, response: null },
        ),
      );
      try {
        await redis.eval(
          COMMIT_BATCH,
          entries.map((e) => k.interrupt(e.interruptId)),
          patches,
        );
      } catch (error) {
        const match = /(missing|nonpending):(\d+)/.exec(String((error as Error)?.message ?? error));
        if (!match) throw error;
        const id = entries[Number(match[2]) - 1]?.interruptId;
        throw new Error(
          match[1] === "missing"
            ? `Interrupt batch references missing id: ${id}.`
            : `Interrupt batch references non-pending id: ${id}.`,
        );
      }
    },

    async get(interruptId) {
      assertId(interruptId, "interruptId");
      return (await redis.json.get<InterruptRecord>(k.interrupt(interruptId))) ?? null;
    },

    async list(threadId) {
      assertId(threadId, "threadId");
      return loadInterrupts(await redis.zrange<string[]>(k.threadInterrupts(threadId), 0, -1));
    },

    async listPending(threadId) {
      return (await interrupts.list(threadId)).filter((r) => r.status === "pending");
    },

    async listByRun(runId) {
      assertId(runId, "runId");
      return loadInterrupts(await redis.zrange<string[]>(k.runInterrupts(runId), 0, -1));
    },

    async listPendingByRun(runId) {
      return (await interrupts.listByRun(runId)).filter((r) => r.status === "pending");
    },
  };

  const metadata: MetadataStore = {
    // Values are wrapped (`{ v }`) so any JSON value, including a bare string, round-trips exactly.
    async get(namespace, key) {
      const doc = await redis.json.get<{ v: unknown }>(k.meta(namespace, key));
      return doc ? doc.v : null;
    },
    async set(namespace, key, value) {
      await redis.json.set(k.meta(namespace, key), "$", { v: value ?? null });
    },
    async delete(namespace, key) {
      await redis.del(k.meta(namespace, key));
    },
  };

  const blobs = config.bucket
    ? upstashBlobStore({
        bucket: config.bucket,
        redis,
        prefix: p,
        ...(config.blobPathPrefix !== undefined ? { pathPrefix: config.blobPathPrefix } : {}),
      })
    : undefined;

  return {
    stores: {
      messages,
      runs,
      interrupts,
      metadata,
      generationRuns: redisGenerationRunStore(redis, p),
      artifacts: redisArtifactStore(redis, p),
      ...(blobs ? { blobs } : {}),
    },
  } as AIPersistence<UpstashPersistenceStores>;
}
