#!/usr/bin/env node
// Stamps each package's own version into its `version.ts` constant, so the telemetry header reports
// the real published version.
//
// This runs at **release time only** (`pnpm ci:version`, right after `changeset version` bumps the
// package.json files), so the constant lands in the release PR alongside the version bump. Builds and
// dev never rewrite tracked source.
//
//   node scripts/sync-version.mjs           # write
//   node scripts/sync-version.mjs --check   # verify only, non-zero exit on drift (used by CI)
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Package dir → the generated constant's path within it.
const TARGETS = {
  "packages/sdk": "src/version.ts",
  "packages/ai-sdk": "src/version.ts",
  "packages/eve": "src/version.ts",
  "packages/eve-extension": "extension/lib/version.ts",
};

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const check = process.argv.includes("--check");
const stale = [];

for (const [pkgDir, target] of Object.entries(TARGETS)) {
  const { version } = JSON.parse(readFileSync(join(root, pkgDir, "package.json"), "utf8"));
  const path = join(root, pkgDir, target);
  const contents = `// Generated by scripts/sync-version.mjs (run by \`pnpm ci:version\`) — do not edit by hand.
export const VERSION = "${version}";
`;

  if (readFileSync(path, "utf8") === contents) continue;
  if (check) stale.push(`${pkgDir}/${target} (expected ${version})`);
  else writeFileSync(path, contents);
}

if (check && stale.length > 0) {
  console.error(
    `Stale version constants — run \`node scripts/sync-version.mjs\`:\n  ${stale.join("\n  ")}`,
  );
  process.exit(1);
}
